# -*- coding: utf-8 -*-
"""Movie Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3RK_5MKJ9xyuPu3SYXCFp6WkUjLGsOh

<h1>Movie Recommendation System</h1>

#<h2>Introduction</h3>

Have you ever watched a movie, loved it, and wanted recommendations on a similar movie to watch? This project aims to help you do that. Using the "*TMDB + IMDB Merged Movies Dataset*" created by Tejas Garg, we'll build a model using CountVectorizer that recommends similar movies based on a movie you give it.

The "TMDB + IMDB Merged Movies Dataset" created by Tejas Garg is under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

Link to dataset:
https://www.kaggle.com/datasets/ggtejas/tmdb-imdb-merged-movies-dataset

#<h2>Part 1: Preparing the Data</h3>

# <h3>Loading the Data</h3>
"""

import pandas as pd

"""When loading the dataset, I used **nrows** in the parameter to only load a certain amount of columns. I will explain why I did this in the next section."""

# loading the datset
df = pd.read_csv('/content/TMDB  IMDB Movies Dataset.csv', nrows=10000)
df.head()

"""# <h3>Cleaning the Data</h3>

The biggest challenges we will be facing in this project isn't training the recommendation system itself; The biggest challenge is using this dataset due to it's large size. This can lead to crashing and excess ram usage. Remember when we used **nrows** to load a certain amount of data? The reason we did this is to significantly lower memory usage and the time it takes to load the data. Without nrows, the memory usage was around 650 MB. That is a high amount of memory usage. Not only would it take a while to load the data, it would lead to crashing later on in project development. Since we used **nrows**, let's see how big this dataset is now.
"""

df.info(verbose=False, memory_usage='deep')

"""As we can see, memory usage is is significantly lower but we want to reduce it more.

Luckily for this project, we're only going to build a Vector model to recommend movies based on text. So we can first reduce the dataset by only including the string columns we need.
"""

df = df[['title', 'overview', 'genres', 'keywords', 'directors']]
df.head()

df.info(verbose=False, memory_usage='deep')

"""By removing unnecessary columns, we were able to further reduce the memory usage. Let's see if we can reduce it further.

Let's check to see if there are any missing values.
"""

df.info()

df.isna().sum()

"""This dataset does contain missing values. Let's remove them."""

# Removing null values
df.dropna(inplace=True)

df.isna().sum()

"""Now let's see if there are any duplicate values."""

df.duplicated().sum()

"""The output shows us there are duplicate values. So let's remove them and confirm if any duplicate values remain."""

df = df.drop_duplicates()

df.duplicated().sum()

"""Let's check the memory usage one last time to see how much it's been reduced to."""

df.info(verbose=False, memory_usage='deep')

"""Adding a new column to the DataFrame called **features** that combines all of the words in the other columns."""

df['features'] = df['title'] + ' ' + df['overview'] + ' ' + df['genres'] + ' ' + df['keywords'] + ' ' + df['directors']

df.info()

"""Tokenizing and vectorizing the **features** column."""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english', min_df=20)
word_matrix = vectorizer.fit_transform(df['features'])
word_matrix.shape

# Making the similarity matrix that will be used in the next section
from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(word_matrix)

"""# <h2>Part 2: Building the Recommendation Model</h2>

# <h3> Building the Model</h3>

Now that we cleaned the data and reduced memory usage for more optimal performance, we can build the model to generate movie recommendations.
"""

# Defining the function to get movie recommendations
def get_recommendations(title, df, sim, count=10):

  # Get the row index of the specified title in the DataFrame
  index = df.index[df['title'].str.lower() == title.lower()]

  # Returns an empty list if there is no entry for the specified title
  if (len(index) == 0):
    return[]

  # Gathers the corresponding row in the similarity matrix
  similarities = list(enumerate(sim[index[0]]))

  # Sorts the similarities in descending order
  recommendations = sorted(similarities, key=lambda x: x[1], reverse=True)

  # Get the top n recommendations, ignoring the first entry in the list since
  # it corresponds to the title itself (and thus has a similarity of 1.0)
  top_recs = recommendations[1:count + 1]

  # Generates a list of titles from the indexes in top_recs
  titles = []

  for i in range(len(top_recs)):
    title = df.iloc[top_recs[i][0]]['title']
    titles.append(title)

  # Return the list of titles
  return titles

"""# <h3>Movie Recommendations</h3>

Now that we've built the model, we can finally test it to get movie recommendations based on a movie we give it.
"""

get_recommendations('The Dark Knight', df, sim)

get_recommendations('Avatar', df, sim)

get_recommendations('Interstellar', df, sim)

get_recommendations('Dumb and Dumber', df, sim)